### ISSUE TITLE
--on and --off parameters not being processed correctly in the DeviceNode.ts example

### ISSUE THREAD

**Issue by JimBuzbee** [project-chip/matter.js#1026]
Executing the example like so:

$ node packages/matter-node.js-examples/dist/esm/examples/DeviceNode.js --on "echo ------------- ON" --off "echo ------------OFF"

When I press "on" in a controller I get the following on the matter.js console:

on:
OnOff is now ON

i.e. no indication that my echo command was executed

**Comment by Apollon77** [comment]
You need to use --on="echo ...." .... so with a sign now... I update the readme
