### ISSUE TITLE
SmartThings Pairing Issue

### ISSUE THREAD

**Issue by JimBuzbee** [project-chip/matter.js#107]
There is some timeout issue with SmartThings during pairing. Lots of activity on the console, but after about four minutes SmartThings gets some sort of timeout and gives an error of "something went wrong". 

But the device is added and functional anyway.

Previously I would get a warning type message in the app that the device had not updated its status yet - try again later, and there would be a battery meter. Both of those issues are now gone. The device is functional, it's just kind of an awkward pairing. 

Log attached

[SmartThingsPairing.log](https://github.com/project-chip/matter.js/files/11304045/SmartThingsPairing.log)

**Comment by Apollon77** [comment]
Ok, in fact same as before ... all the stiff happens within 8 seconds and then he has subscribed. nothing more happens afterwards from the  smartthings side ... no idea what he expects regarding timeout

**Comment by JimBuzbee** [comment]
Attached are two more logs of a pairing that gave a generic error, but added the device anyway - fully functional. One log from the Android side, one from the node-matter side.  

Also, I forgot to mention that occasionally the pairing succeeds with no error from SmartThings.  But, again, this is from a pairing that gave an error. 

I recall that with previous logs from the Android side, I was able find an error message that indicated "timeout", but this time I do not see that.


[SmartThingsPairingAndroid1.log](https://github.com/project-chip/matter.js/files/11304300/SmartThingsPairingAndroid1.log)
[SmartThingsPairing1.log](https://github.com/project-chip/matter.js/files/11304301/SmartThingsPairing1.log)

**Comment by Apollon77** [comment]
Ok, the Smartthings log is not that helpful. too cryptic and I can not see any connection to the other communicatoon ... se no idea ... Also nothign "unknown" or anything. But I do not see anything else  ... so it stays strange
