### ISSUE TITLE
matter-node.js do not re-export matter.js/node

### ISSUE THREAD

**Issue by alexojegu** [project-chip/matter.js#1145]
`matter-node.js` do not re-export `matter.js/node`:

```
src/matterBridge.ts:1:28 - error TS2307: Cannot find module '@project-chip/matter-node.js/node' or its corresponding type declarations.

1 import { ServerNode } from "@project-chip/matter-node.js/node";
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
From README:

> - **[matter-node.js](./packages/matter-node.js)**: a node.js implementation of a Matter DeviceNode and ControllerNode which also re-exports all matter.js exports and so can be used as only dependency. It is build and published as CommonJS and ES6 variants in one package.

**Comment by Apollon77** [comment]
Yes this is a change in 0.10, I will adjust the README to the new reality asap.

The exports of matter.js package got too complex to easiely mimic in matter-node, so only some parts are still exported on matter-node.js.

Ideally change to use matter.js AND matter-node.js in your dependencies and make sure it is in the same verison and only do one generic matter-node import to initialize the node-js relevant environment. And import the rest directly from matter.js

**Comment by Apollon77** [comment]
PS: The readme of the matter-node.js package was clear on that already, but I clean that up now
