### ISSUE TITLE
Don't fail for conformance issues where the spec provides a default value

### ISSUE THREAD

**Issue by jpadie** [project-chip/matter.js#1162]
example: a color light device that supports color temperature requires ColorTempPhysicalMaxMireds to be set as an attribute and will fail conformance fatally if not supplied.  However there is a specified default value for this attribute.  

would it not make more sense for the default value to be imputed if no express value is provided?

**Comment by Apollon77** [comment]
Please add details and the exception and composition information. Because we exactly use the defaults and that should not give any conformance errors (if the default is valid for a certain  feature combination).

Could it be related to #1161 ?

**Comment by jpadie** [comment]
strangely I am not able to replicate the use case on either the previous installed base or a fresh one. 
the scenario I was getting yesterday was conformance failures for not setting all the MS *MIRED attributes. ditto the mandatory attribute (for which there is a default).  unless I removed colorTemperature from the features.  

Today the device is instantiating correctly whatever the scenario. 

The only difference is that today I am trying to build the test case as a standalone.  When I have more time I will try again with the device as part of a bridge; but I don't see why that should have any impact at all.

**Comment by Apollon77** [comment]
Then please reopen when you can repro and are sure not connected with "device type or cluster/feature changes"
