### ISSUE TITLE
Clean fabric

### ISSUE THREAD

**Issue by lboue** [project-chip/matter.js#117]
Hello,

Could you add the procedure to remove the pairing and reset the node?

Regards

**Comment by lboue** [comment]
I noticed with that command it worked:
```
rm device-node/FabricManager.fabrics
```

**Comment by Apollon77** [comment]
In fact you need ideally to kill the whole storage dir because also in other places (e.g. session manager) there could be data that should also be removed

**Comment by Apollon77** [comment]
done differently via new parameter -cleastorage

**Comment by lboue** [comment]
Thanks
