### ISSUE TITLE
"BLE is not supported on this platform", what does it mean?

### ISSUE THREAD

**Issue by tomxue** [project-chip/matter.js#1277]
![image](https://github.com/user-attachments/assets/10e00627-3ae6-4b48-bd10-e8af51c4b133)

I run matter.js shell and hope to commission my matter device via BLE on Windows, but got above error.
What does it mean of "BLE is not supported on this platform"? Not supported on Windows?

**Comment by Apollon77** [comment]
In fact the answer is a typical "RTFM" ;-)))

look at the shell reame ... and then adjust your call to 

`npm run shell -- --ble`

**Comment by Apollon77** [comment]
PS: But it still might not work on windows ... see also https://github.com/project-chip/matter.js/discussions/1241
