### ISSUE TITLE
MdnsService Unknown interface: eth1

### ISSUE THREAD

**Issue by Controlhaus** [project-chip/matter.js#1304]
Testing on a device with 2 network adapters (`eth0` and `eth1`) causes the app to crash when `eth1` is not connected.

Error log is attached.
[Unknown interface eth1.txt](https://github.com/user-attachments/files/17485980/Unknown.interface.eth1.txt)

**Comment by Apollon77** [comment]
And you are sure that not eth1 was set as "netInterface to use"? Because I checked the code and could only find this as a case for this crash

**Comment by Controlhaus** [comment]
`MATTER_MDNS_NETWORKINTERFACE` is set to `eth0`

`export MATTER_MDNS_NETWORKINTERFACE=eth0`

**Comment by Controlhaus** [comment]
Closing. The application stops like it should if an unavailable ethernet adapter is defined.
