### ISSUE TITLE
Confusion between @project-chip and @matter npm repos

### ISSUE THREAD

**Issue by rcaceiro** [project-chip/matter.js#1336]
Hello everyone,

I know that version 0.11 is still in development, but I’m unsure which repository to use. Most examples target @matter.js later @matter, but about a month ago, it stopped receiving updates, and @project-chip restarted development. However, @matter seems more complete. Which one should we use to start a new project?

**Comment by Apollon77** [comment]
0.11 was released today (n 26 mins before your issue opened *gg*) ... so @matter is the new main home.

@project-chip/matter.js is still needed for some "legacy" cases and currently Controller building. The examples show how to best use it

**Comment by rcaceiro** [comment]
Thank you @Apollon77
