### ISSUE TITLE
Deprecated `FanMode.On` write rejected when spec says it shall result in `FanMode.High`

### ISSUE THREAD

**Issue by kennylevinsen** [project-chip/matter.js#1476]
When implementing the fan control cluster in home-assistant-matter-hub, I found that Google Home writes the deprecated `FanMode.On` to `fanMode` followed by a `percentageSetting` when it is told to set a fan to a specific percentage.

This leads to the following error (`4` is `FanMode.On`):

```
[ DEBUG ] [ Matter / Behavior          ]: Read dd1dc8f31c494cdd9c94587f14ce15b5.aggregator.fan_living_room.fanControl.state.fanMode via online#4d3ca48@b55c83b
[ INFO  ] [ Matter / Behavior          ]: Write dd1dc8f31c494cdd9c94587f14ce15b5.aggregator.fan_living_room.fanControl.state.fanMode via online#4d3ca48@b55c83b
[ DEBUG ] [ Matter / Transaction       ]: Transaction online#4d3ca48@b55c83b locked dd1dc8f31c494cdd9c94587f14ce15b5.aggregator.fan_living_room.fanControl.state
[ ERROR ] [ Matter / Transaction       ]: Rolling back online#4d3ca48@b55c83b due to error: Validating dd1dc8f31c494cdd9c94587f14ce15b5.aggregator.fan_living_room.fanControl.state: Value "4" is not defined in enum (135)
[ DEBUG ] [ Matter / Transaction       ]: Transaction online#4d3ca48@b55c83b rolled back and unlocked 1 resource
[ ERROR ] [ Matter / InteractionServer ]: Error while handling write request from udp://fd86:65b0:bc8:f49:912a:8624:8631:96d2:5540 on session secure/59664 to Fan(0x2)/FanControl(0x202)/fanMode(0x0): Validating dd1dc8f31c494cdd9c94587f14ce15b5.aggregator.fan_living_room.fanControl.state: Value "4" is not defined in enum (135)
```

However, the spec seems to have a quite clear expected behavior when a client writes the deprecated fan modes:

```
4.4.6.1.3. On Value
If a client attempts to write a value of On, the attribute SHALL be set to High.

4.4.6.1.4. Smart Value
If a client attempts to write a value of Smart and the AUT feature is supported, the attribute SHALL
be set to Auto, otherwise the attribute SHALL be set to High.
```

(The wording from before 1.2 did not have the `AUT` feature exception, but otherwise matches in requirements.)

While the use of `FanMode.On` is presumably an error from the Google Home side (the name is enticing enough that I too had used it before reading the fineprint), the resulting error seems to clash with the wording of the spec.

Relates to:
- https://github.com/t0bst4r/home-assistant-matter-hub/pull/258

**Comment by Apollon77** [comment]
Yes, the  Enum value should not be disallowed because of being Deprecated. We need to fix this

**Comment by Apollon77** [comment]
Should be fixed by PR that merges soon, will be in nightly, but I also plan to release 0.11.9 tomorrow

**Comment by kennylevinsen** [comment]
Thanks for the speedy fix!
