### ISSUE TITLE
Does this repository implement the Matter protocol completely 

### ISSUE THREAD

**Issue by Jardaliao** [project-chip/matter.js#1480]
I can't find any branch like v1.1-branch, v1.2-branch.

If I want to build a controller, which branch should I use?

**Comment by Jardaliao** [comment]
Oh I found the document [https://github.com/project-chip/matter.js/blob/main/docs/MATTER_COMPATIBILITY.md](url)

**Comment by Jardaliao** [comment]
Oh I found the document [https://github.com/project-chip/matter.js/blob/main/docs/MATTER_COMPATIBILITY.md](https://github.com/project-chip/matter.js/issues/url)

**Comment by Apollon77** [comment]
Yes, this document tries to summaries the current status. When you want to build a controller I would propose you use the latest 0.11. versions from npm. We are currently finished some quality topics ad then we will start preparing 0.12 which will also get Matter 1.4 support
