### ISSUE TITLE
Leviton Node connection issues

### ISSUE THREAD

**Issue by digitaldan** [project-chip/matter.js#1519]
As discussed on discord, i have a few Leviton wifi switches and dimmers who get into a bad state and matter.js can not establish a connection to them even though they are on the network and can be pinged (both ipv4 and ipv6).  Attached is a log of one trying to reconnect as discussed. Running 0.11.9-alpha.0-20241209-06a8040e1

[node-8870212737446009434-3-clean.log](https://github.com/user-attachments/files/18133049/node-8870212737446009434-3-clean.log)

**Comment by digitaldan** [comment]
Here's another one for node 8870212737446009434 running v0.12.0-alpha.0-20241220-2c53108aa , this log has several reconnect attempts

[node-8870212737446009434-4.log](https://github.com/user-attachments/files/18213685/node-8870212737446009434-4.log)

**Comment by Apollon77** [comment]
Ok, after multiple tries I think the conclusion is that the device is strange ... so nothing I see that make sense to tweak in matter.js for now
