### ISSUE TITLE
Composed Device failure with SmartThings

### ISSUE THREAD

**Issue by JimBuzbee** [project-chip/matter.js#179]
Paired the example Composed Device with SmartThings (with the usual timeout) but after completion only a single device was shown instead of the expected two. Attempts to turn the single device on/off generated errors within the SmartThings app. Attached log shows the pairing process followed by several attempts to control the single displayed device.

[SmartThings-ComposedDeviceNode.txt](https://github.com/project-chip/matter.js/files/11647355/SmartThings-ComposedDeviceNode.txt)

**Comment by Apollon77** [comment]
Ookkk interesting. 

It analyzes the structure correctly but then for controlling:

> InteractionProtocol Received invoke request from udp://fe80::26fd:5bff:fe03:cc52%en0:58587 on session secure/30292: MA-onofflight(0x1)/unknown(0x6)/0x1
2023-06-04 16:31:20.815 ERROR InteractionProtocol Unknown command MA-onofflight(0x1)/unknown(0x6)/0x1

He calls the OnOff cluster on the wrong endpoint. But always. Do the Ingo you gave that turning on worked I can not see in log (but I also only see off command requests. Ok just on mobile. Maybe I missed a call)

**Comment by Apollon77** [comment]
Closed because seems smartthings lack composed device support for now
