### ISSUE TITLE
Failing to delete device with Google Home

### ISSUE THREAD

**Issue by JimBuzbee** [project-chip/matter.js#181]
Google hangs when trying to delete newly paired device (not after matter.js restart). 

Log attached

[session.txt](https://github.com/project-chip/matter.js/files/11761170/session.txt)

**Comment by Apollon77** [comment]
In fact this is no error. The log shows that fabric Index 1 got created and then deleted.

The specs say the following for this:

> ... all data needs to be removed ... Since this operation involves the removal of the secure session data that may under­ pin the current set of exchanges, the Node invoking the command SHOULD NOT expect a response before terminating its secure session with the target.

And in fact this happens here.

The log shows the removeFabric and that we respond with ok for it (in fact) with the proper ack message. But then the session is deleted.

So the ack from Google that they received our "ok" message can not be processed anymore, hence the invalid sessions.

But in fact the device should be deleted in Google. Or is it staying there? Try reload the app? SOmetimes they have caching issues in such cases where app still shows removed devices.

**Comment by JimBuzbee** [comment]
I tried again this morning with Google Home and had similar results.

- Create the device successfully.
- Delete the device in Google Home
- Google Home shows full-screen white with spinner
- Log file displaying repeating "Cannot find a session for ID nnnn" messages and "The previous message has not been acked yet, cannot send a new message"
- Wait 5 minutes or so - Google Home still showing white screen with spinner
- Restart Google Home
- Device still shown
- Try deleting again
- Log file shows repeating "Cannot find a session for ID nnnn" messages
- Google Home briefly shows spinner, then returns to delete screen
- Device still shown in Google home
- Try deleting again
- Success in Google Home!
- Device is gone

**Comment by mow** [comment]
the same applies to me and as far as I know I'm not opted-in for a public preview, it happens every time, easily reproducible. when matter bridge device is *killed* then it deletes a bit more fast, otherwise I try 2-3 times to remove.

**Comment by Apollon77** [comment]
I need to look into that ... and also compare with apple ... but in fact we should do anything right

**Comment by Apollon77** [comment]
@JimBuzbee can you pkease recheck on main ?

**Comment by JimBuzbee** [comment]
Matter.js Device deletes cleanly and quickly from Google Home using main as of Aug 17.

**Comment by Apollon77** [comment]
Thank you!
