### ISSUE TITLE
matter-node Cannot pair Bridge after deleting.

### ISSUE THREAD

**Issue by Controlhaus** [project-chip/matter.js#202]
Unable to pair a Bridge a second time after deleting the previously paired bridge in the smart home app (tested with Apple Home).

The Bridge pairs successfully again after deleting the storage directory.

Edit: Here are the log entries from matter-node after pressing delete in Apple Home:
[2023-07-13 17:30:18.txt](https://github.com/project-chip/matter.js/files/12041119/2023-07-13.17.30.18.txt)

**Comment by Apollon77** [comment]
This is an iOS bug. iOS creates two fabrics on commissioning, but only deletes one when deleting the device. so the one fabric left still makes the devcie logic think it is commissioned. Rigth now only way is to manually clear the storage. I tested in in Google Home and there it works correctly (and also Apple wasnworking <iOS 16.5.1 - no idea which exaxt version)!

We should try in iOS 17 and if still an issue report it

**Comment by Apollon77** [comment]
I added it to the known issues list in #213

**Comment by Apollon77** [comment]
So this is "as designed by Apple". When deleting a device in Apple home you also need to delete it in "Settings - General - Matter-Devices" additionally. 

--> see https://github.com/project-chip/connectedhomeip/issues/29284#issuecomment-1732372979
