### ISSUE TITLE
InteractionProtocol */0x31/0x3 unsupported path

### ISSUE THREAD

**Issue by adminy** [project-chip/matter.js#208]
InteractionProtocol Read from udp://fe80::1424:8341:502a:f033%wlan0:55462 on session secure/62366: */0x31/0x3 unsupported path

[here are the logs](https://logpaste.com/UJLgUtcw)

And [here](https://raw.githubusercontent.com/adminy/home/master/index.js) is the code running the device.

**Comment by Apollon77** [comment]
Fixed by https://github.com/project-chip/matter.js/pull/210
