### ISSUE TITLE
Failing to pair with Google Home on Android - 7/18 baseline

### ISSUE THREAD

**Issue by JimBuzbee** [project-chip/matter.js#220]
Pairing with Google Home on Android fails 

Using a fresh clone on 7/18 followed by:

cd matter.js
npm i
npm run  matter-device

UI reports "Something went wrong"

Log attached. Separately, paring succeeded with IOS, Amazon and SmartThings.

[mater.txt](https://github.com/project-chip/matter.js/files/12089001/mater.txt)

**Comment by Apollon77** [comment]
I suspect: Invalid regulatory location  error because we check it now ... 

They want to set "IndoorOutdoor which makes no sense. I provide a PR to ignore this
