### ISSUE TITLE
Failing to commision on Google Home Android

### ISSUE THREAD

**Issue by JimBuzbee** [project-chip/matter.js#237]
Fresh July 27 clone of baseline

Success on: Apple, Alexa, SmartThings, Rainmaker
Failure on Google Home. UI starts the process but sticks "forever" on "Connecting to Device"

Log attached.

[ghome.txt](https://github.com/project-chip/matter.js/files/12186593/ghome.txt)

**Comment by Apollon77** [comment]
I also stubled over that theoretically as a potential issue with the new clusters, I will investigate!

**Comment by Apollon77** [comment]
partly caused by https://github.com/project-chip/matter.js/issues/239

**Comment by Apollon77** [comment]
should be fixed in main since longer time
