### ISSUE TITLE
Controller able to get status but doesn't receive live updates

### ISSUE THREAD

**Issue by FezVrasta** [project-chip/matter.js#297]
Hi, for some reason the controller example (and the code I derived from it) is only giving me the initial state but doesn't (always) provides live updates, I was able to receive them only once.

What can I do to understand why live updates are not flowing?

https://github.com/FezVrasta/node-red-matter/blob/master/src/modules/matter-controller.ts

The above is my code.

I'm also confused on how the controller example works, I can pair a device, but if the device pairing is not enabled anymore when I restart the matter server it will fail to pair again. This can happen if I generate a pairing code from Apple Home for example.

**Comment by FezVrasta** [comment]
Most of the times it doesn't even get the initial status for some reason:

<img width="489" alt="CleanShot 2023-08-29 at 6 45 17@2x" src="https://github.com/project-chip/matter.js/assets/5382443/b5931b8e-1e46-42da-b718-6e181c5307a0">

But if I enable the debug logging I see the CommissionController attribute log reporting the state changed.

<img width="734" alt="CleanShot 2023-08-29 at 6 46 15@2x" src="https://github.com/project-chip/matter.js/assets/5382443/01e49dd9-bcbe-4a03-9881-e7433956969e">

**Comment by FezVrasta** [comment]
It's not clear to me why there's this code here:

```
      if (devices[0] && devices[0].id === 1) {

```

In my case `devices[0]` has 2 as id, not 1. But if I change the check to `=== 2` it can retrieve the status with `getOnOffAttribute()` and react to changes when `.toggle()` is called, but no changes made from the paired device node itself are caught by the listener.

**Comment by Apollon77** [comment]
First ok all regading your code ... what is https://github.com/FezVrasta/node-red-matter/blob/master/src/modules/matter-controller.ts#L58 ?? This method do not exist. your "onStateChange" is a method in the object and so you would need to use this.onSateChange bt that would not make any sense ... So are you sure that your code is correct?

Additionally: The example code is mainly there for a normal "onoff device" with a root endpoint and then an onoff as endpoint id 1. This means when your divice is different in endpoint that you also need to parse the data differently or you need to programnmatically iterate the devices array or such to see whats really in. Also the endpoint logging as in example script might help.

**Comment by Apollon77** [comment]
PS: Your screenshot from above should look like it would needs to be on receiving a state change. when there is ahandler then it is used.

SO if you need more help please post the endpoint logger output and we can check tiogether what is what.

**Comment by FezVrasta** [comment]
> First ok all regading your code ... what is https://github.com/FezVrasta/node-red-matter/blob/master/src/modules/matter-controller.ts#L58 ?? This method do not exist. your "onStateChange" is a method in the object and so you would need to use this.onSateChange bt that would not make any sense ... So are you sure that your code is correct?

The way it's written is a bit confusing, it's actually a onStatusChange method that takes as argument a callback with the same name, it's just some code I put quickly together, I'll change it to be clearer.

> Additionally: The example code is mainly there for a normal "onoff device" with a root endpoint and then an onoff as endpoint id 1. This means when your divice is different in endpoint that you also need to parse the data differently or you need to programnmatically iterate the devices array or such to see whats really in. Also the endpoint logging as in example script might help.

I have been testing it with a simple on/off device created by matter.js too (but on a different matter server instance)


---

I'll provide more details as soon I get back to my computer

**Comment by FezVrasta** [comment]
I'm unable to reproduce the issue today, I'm not really sure what happened. I'll report back if it happens again.
