### ISSUE TITLE
Cluster specific StatusCode structure are not generated

### ISSUE THREAD

**Issue by Apollon77** [project-chip/matter.js#311]
Example: https://github.com/project-chip/matter.js/blob/main/packages/matter.js/src/model/standard/elements/AdministratorCommissioning.ts#L245-L265 is defining custom StatusCodes,

they are not included in the generated TypeScript

**Comment by lauckhart** [comment]
Haven't forgotten about this, #318 has updates to code gen stuff, once it's in I'll take care of this.
