### ISSUE TITLE
[test] Add browser compatibility tests to CI

### ISSUE THREAD

**Issue by turon** [project-chip/matter.js#32]
The test framework is designed to run browser compatibility tests, but those aren't run in by the CI to validate PRs don't break browser compatibility.  Add the browser tests to CI.

**Comment by Apollon77** [comment]
@turon How these tests are supposed to run at all? For me locally starting the tests spin up a browser but then nothing happens

**Comment by mfucci** [comment]
Yes, they work. The output is in the terminal, not in the browser.

**Comment by Apollon77** [comment]
ok, will check again ... I did not saw anything ... maybe a macos issue? it was just hanging

**Comment by turon** [comment]
was there a PR that closed this issue?

**Comment by Apollon77** [comment]
(At least in my pov)
