### ISSUE TITLE
Failed to add example device on Windows

### ISSUE THREAD

**Issue by vilic** [project-chip/matter.js#359]
I am trying to pair a `matter-node.js` example device on Windows 11 with Apple Home, but overall, it fails predicably.

Output pairing via Bluetooth (5.3 adapter with WinUSB driver): https://gist.github.com/vilic/5d90880764d53d5eea6d4bbb989d540f

Pairing without Bluetooth is even harder, and I haven't got one single complete success. Most of the time it fails to connect at the beginning.

It turns out that interface name in IPv6 address gets ignored and falls back to seemingly unpredictable interface if there's multiple ones. In my case, I have `Wi-Fi` and `vEthernet (Default Switch)`, and `::%<name>` always falls back to the second one, and making the pairing unsuccessful.

**Comment by vilic** [comment]
PR #360 fixes pairing over network (Wi-Fi) on Windows with multiple network interfaces, ~~and also makes pairing via Bluetooth closer to success (device can be added successfully, but stuck on "updating")~~ (seems to succeed reliably now).

**Comment by Apollon77** [comment]
Thank you, I agree: BTP and all looks fine it just stops when the connection should switch to the IP network, so most likely the fix is for that, I also saw another exception which is unexpected (the update fabric one). WOuld you be so kind and create another issue for that ... I have the fix already locally and will push that too then.

**Comment by vilic** [comment]
@Apollon77 Sure, will create a new issue later. :D

**Comment by Apollon77** [comment]
Thank you. And one other question: when you tackled windows and there is anything that might help others to get it running a PR for the matter-node.js readme or such would be awesome with these tips ;-) thank you in advance

**Comment by vilic** [comment]
@Apollon77 You're welcome. Would love to help, but for now the blocking issues I encountered have already been addressed by my recent PRs.

The only tip missing might be that: `@abondonware/noble` on Windows might require Visual Studio 2022 to build but the built-in installation script of Node.js Windows installer installs version 2019. But I can't think of a good place for that tip, ideally a script synchronizing across READMEs in several relevant places would be nice.

Other than that, getting started guide is missing but that's not Windows-specific.

**Comment by Apollon77** [comment]
So just download and install Visual studio 2022 dist files ro what a windows user should do? :-)

**Comment by vilic** [comment]
> So just download and install Visual studio 2022 dist files ro what a windows user should do? :-)

I think you may refer to `node-gyp` installation guide (https://github.com/nodejs/node-gyp#on-windows) and inform the necessity of version 2022. That should be good enough for IMO.
