### ISSUE TITLE
Change listening on SIGINT in matter-node.js to beforeExit event

### ISSUE THREAD

**Issue by vilicvane** [project-chip/matter.js#424]
Adding a listener to SIGINT removes the default behavior of Node.js (exiting the process):

https://github.com/project-chip/matter.js/blame/28e66b481132b34acc54938363a2536a65155d89/packages/matter-node.js/src/net/register.ts#L19

Currently this does nothing, so is it a little bit early to add this stuff? If not, ever considered using [`beforeExit`](https://nodejs.org/api/process.html#event-beforeexit) event?

**Comment by Apollon77** [comment]
I work now many years in node.js and never stumpled over this event ... beforeExit sounds like the best place for now ...
