### ISSUE TITLE
Validate "incoming" (decoded) data to defined shema breaks with List chunking

### ISSUE THREAD

**Issue by Apollon77** [project-chip/matter.js#48]
While playing around with node-matter and pairing as controlelr with chip-tool lighting app I came across the protocol options for array/List chunking.

The chip app always send an empty array and then "add" elements to it in additional packages. This is in fact also needed if an array gets that big that it do not fit in one data package.
While this topic itself can not be handled on "pure Tlv level" (aka /src/tlv/TlvArray.ts) the current issue starts when we have a schema with e.g. "minimum 1 list entry". Because decoding the first tlv package gives an empty array and this will fail because we do validation.

The main question that arises is: If devices is sending a invalid value (aka "decode for the library), should that be an exception? In fact we can not do anything against such "Misbehaving devices". In fact yes, it should be still an exception if we want to encode (aka send ourself) such a value, so the shema validation should be used when setting such a value.

The alternative would be to allow a flag when decoding values to not validate the value and the caller ist then self-responsible. (so after processing all value parts we could call validate ourself)

Details for that "Change" (Chunking) handling is in Core Specs "10.5.4.3.1. Lists".

As an example this is the DataReport received from chip tool app for reading one value:

```
{
    "values": [
        {
            "value": {
                "version": 2206465283,
                "path": {
                    "endpointId": 0,
                    "clusterId": 29,
                    "attributeId": 0
                },
                "value": [
                    {
                        "typeLength": {
                            "type": 22
                        }
                    },
                    {
                        "typeLength": {
                            "type": 24
                        }
                    }
                ]
            }
        },
        {
            "value": {
                "version": 2206465283,
                "path": {
                    "endpointId": 0,
                    "clusterId": 29,
                    "attributeId": 0,
                    "listIndex": null
                },
                "value": [
                    {
                        "typeLength": {
                            "type": 21
                        }
                    },
                    {
                        "tag": {
                            "id": 0
                        },
                        "typeLength": {
                            "type": 4,
                            "length": 0
                        },
                        "value": 22
                    },
                    {
                        "tag": {
                            "id": 1
                        },
                        "typeLength": {
                            "type": 4,
                            "length": 0
                        },
                        "value": 1
                    },
                    {
                        "typeLength": {
                            "type": 24
                        }
                    }
                ]
            }
        }
    ],
    "suppressResponse": true,
    "interactionModelRevision": 1
}
```

The "Change" logic is within the listIndex field when getting attribute responses. In this case listIndex=null means "add these data to the array".

**Comment by Apollon77** [comment]
@mfucci @turon Whats your opinions on that topic?

**Comment by mfucci** [comment]
Maybe a PartialTlv object that wraps a TLV schema but skip validation when we know is is just a partial chunk?
Ideally, we want to wait to have all the chunks, merge the data and then validate them.

Alternatively, we can add a flag to skip validation on chunked packets, but not sure when to do it then.

**Comment by Apollon77** [comment]
In fact my current working idea would be: Add a "skipCalidation2 Flag to decode methods that skips validation. Then in the code place where the "DataReport" is handled do exactly that:
* if just one chunk came in call decode with doing validation as normally
* on multiple chunks process them without validation and then call one schema validation on the result "manually"

I have this already haldf done locally. The only question is if this "composition" should be in the "tlv" part and classes which would mean to wrap the data to transport that listEntry element for the processing. Or if we just leave this logic in "the one place" where the DataReport is processed. I would favour the latter for now ... we can move it later too.

I could give it a shot

**Comment by mfucci** [comment]
Maybe a simple temporary solution is to accept empty array in those data structure, even if this doesn't respect the specs, with a big TODO to better control later.

Given the huge scope of remaining work we have to do, this seems a lower priority and won't bring much value. So we might add those extra checks when everything else is compliant.

Implement this right doesn't seem that simple to me and might introduce extra complexity and bugs... so maybe better to delay.

**Comment by Apollon77** [comment]
Maybe lets have it as topic in the call ... a skipValidation flag could also be removed later :-) and we would only use that "in the case we need it", so in most cases we will do the checks ... just when parsing DatsaReports in Controller mode we would use a special case ...

**Comment by Apollon77** [comment]
#49 can support here
