### ISSUE TITLE
Need to override OnOffClusterDefaultHandler

### ISSUE THREAD

**Issue by antonio-gabriele** [project-chip/matter.js#526]
Dear,
I need to override OnOffClusterDefaultHandler class because in the real life on, off, etc commands must not modify directly attribute, but they need to send command to physical peripheral. Peripheral will send command response that update the attribute OnOff. This is true for all clusters. Do you plan a convenient way to create a Dynamic Device with capabilities to add cluster ad intercept command at runtime?

**Comment by lauckhart** [comment]
Yes, that's under active development, will hopefully make it into the 0.8 release.

**Comment by Apollon77** [comment]
Exactly. ;-)

Currently in code today you can simply override the onoffcluster or use setCommandHandler and override on and off and toggle.

**Comment by antonio-gabriele** [comment]
Thanks. I did simply override and now it works. Now I get
device.getClusterServer(LevelControl.Cluster)?.setCurrentLevelAttribute(10) don't update the App.
In the log I have 2023-11-18 22:10:36.358 DEBUG ClusterServer Storing attribute onOff in cluster OnOff (6)
Do you have any suggestion?

**Comment by Apollon77** [comment]
Ok now you need to be more detailed please. Ideally post the code on how you did override and also full log because changing level and then OnOff changed is strange.

**Comment by antonio-gabriele** [comment]
Dear,
this is my Device class:

```
import {
  ClusterClient,
  ClusterServer,
  ClusterServerHandlers,
  Identify,
  LevelControl,
  LevelControlCluster,
  OnOff,
  OnOffCluster,
  createDefaultGroupsClusterServer,
  createDefaultIdentifyClusterServer,
  createDefaultScenesClusterServer
} from "@project-chip/matter-node.js/cluster";
import { extendPublicHandlerMethods } from "@project-chip/matter-node.js/util";
import { Device, DeviceTypeDefinition, WrapCommandHandler } from "@project-chip/matter-node.js/device";

type BaseDeviceCommands = {
  identify: ClusterServerHandlers<typeof Identify.Cluster>["identify"];
};

export class DeviceCreator extends extendPublicHandlerMethods<typeof Device, BaseDeviceCommands>(Device) {

  constructor(deviceTypeDefinition: DeviceTypeDefinition) {
    super(deviceTypeDefinition);
    this.addClusterServer(
      createDefaultIdentifyClusterServer({
        identify: async () => { },
      }),
    );
    this.addClusterServer(createDefaultGroupsClusterServer());
    this.addClusterServer(createDefaultScenesClusterServer());
  }

  addOnOffServer(onOffClusterHandler: ClusterServerHandlers<typeof OnOff.Base>) {
    this.addClusterServer(ClusterServer(OnOffCluster,
      { onOff: false, }, WrapCommandHandler(onOffClusterHandler, this.commandHandler)));
  }

  addLevelControlServer(levelControlClusterHandler: ClusterServerHandlers<typeof LevelControl.Base>) {
    this.addClusterServer(ClusterServer(LevelControlCluster, {
      currentLevel: 0,
      options: undefined,
      onLevel: 0
    }, WrapCommandHandler(levelControlClusterHandler, this.commandHandler)));
  }

}

```
This is how I use it.

```
deviceFactory.addOnOffServer({
        on: async () => {
          control.write(true);
        },
        off: async () => {
          control.write(false);
        },
        toggle: async ({ attributes: { onOff } }) => {
          control.write(!onOff);
        }
      });

this.aggregator.addBridgedDevice(deviceFactory, {
      nodeLabel: name,
      productName: name,
      productLabel: name,
      serialNumber: `konnex-${uniqueId}`,
      reachable: true,
    });
```

`deviceFactory.getClusterServer(OnOff.Cluster)?.setOnOffAttribute(!!newValue);`

This is the console log when i run that line:

0/0/2 <- true //I clicked KNX toggle switch
2023-11-19 09:36:51.200 DEBUG ClusterServer Storing attribute onOff in cluster OnOff (6)
0/0/2 <- false //I clicked KNX toggle switch
2023-11-19 09:36:52.136 DEBUG ClusterServer Storing attribute onOff in cluster OnOff (6)
0/0/2 <- true //I clicked KNX toggle switch
2023-11-19 09:36:56.515 DEBUG ClusterServer Storing attribute onOff in cluster OnOff (6)

Using your OnOffLightDevice I get:
```
2023-11-19 09:42:16.654 DEBUG ClusterServer Storing attribute onOff in cluster OnOff (6)
2023-11-19 09:42:16.713 DEBUG SubscriptionHandler Sending subscription update message for ID 3706006465 with 1 attributes and 0 events
2023-11-19 09:42:16.714 DEBUG MessageExchange New exchange protocol: 1 id: 36355 session: secure/27813 peerSessionId: 54755 active retransmit ms: 300 idle retransmit ms: 5000 retries: 5
2023-11-19 09:42:16.714 DEBUG SubscriptionHandler Sending subscription changes for ID 3706006465: MA-onofflight(0x12)/OnOff(0x6)/onOff(0x0)=true (2339703863)
2023-11-19 09:42:16.715 DEBUG InteractionMessenger Sending DataReport chunk with 1 attributes and 0 events: 41 bytes
2023-11-19 09:42:16.715 DEBUG ExchangeManager Message » id: 54755/36355/359627568 type: 1/5 reqAck: true payload: 152600c12be5dc36011535012600370c758b3701240212240306240400182902181818280424ff0a18
2023-11-19 09:42:16.742 DEBUG MessageExchange Message « id: 27813/36355/233618390 type: 1/1 acked: 359627568 reqAck: true payload: 1524000024ff0118
2023-11-19 09:42:16.742 DEBUG ExchangeManager Message » id: 54755/36355/359627569 type: 0/16 acked: 233618390 reqAck: false payload: 
```

Please let me know.

**Comment by Apollon77** [comment]
And you are sure that the subscription was established by the controller after the device start and you tried it? Depending on your timing this might needs 1-3mins sometimes after a restart. Because the log shows that value got stored, so in general your cluster is "used" ... but seems not subscribed. (Guessing ....)

**Comment by antonio-gabriele** [comment]
I'm inspecting the issue. Behaviour is inconsistent, but i'm on it.
