### ISSUE TITLE
Is there a matter.js version of the light-switch example program?

### ISSUE THREAD

**Issue by whqxbs** [project-chip/matter.js#533]
Dear, 

I initially used the ESP32 example program in `connectedhomeip/examples/light-switch-app` with acl and binding cluster to implement the ESP32 development board to control the light on/off. But because of some problems ESP32 physical device is not very convenient for my debugging, so I want to use matter.js project to generate virtual switch and light so that it is more convenient to carry out related tests.

I found `DeviceNode.ts` is the sample program for the light, but I didn't find the sample program for the switch, where can I get it please? Or is there any good brother who has implemented the matter.js code for this switch and could you share it for me? Thanks a lot!

Thanks and looking forward to your replies!

**Comment by antonio-gabriele** [comment]
Go there.
https://github.com/antonio-gabriele/matter-test/tree/main/src

**Comment by whqxbs** [comment]
> Go there. https://github.com/antonio-gabriele/matter-test/tree/main/src

I can't quite read the code you provided, but it looks very interesting!
Is this repository of yours being tested for matter security? Can you tell me how to deploy your code?

**Comment by Apollon77** [comment]
To copy the respond from Discord:

The ClusterClient integration for devices and Binding logic in general (and also ACL needed for that) is still on the todo list for matter.js, sorry. So not yet available. i currently work towards this by adding groups, after this acl and after this binding/Client topics ...

**Comment by Apollon77** [comment]
duplicate to #166

**Comment by whqxbs** [comment]
OK. Thanks for your answer :-) .
