### ISSUE TITLE
NotImplementedError: Devices with client clusters are not supported yet

### ISSUE THREAD

**Issue by antonio-gabriele** [project-chip/matter.js#596]
Hi all, I'm planning to manage client cluster on my project https://github.com/antonio-gabriele/zigbee-matter-bridge to support switch buttons. When will be client cluster supported?
Thankls for your work.
Regards.

**Comment by Apollon77** [comment]
See https://github.com/orgs/project-chip/projects/11

Groups and acl are prerequisites for this and so they are planned first. Bindings are planned afterwards. I already work on groups in parallel to finalizing the new full device type class support.

**Comment by Apollon77** [comment]
Closed because tracked in project.
