### ISSUE TITLE
Wifi Credentials with spaces in the SSID

### ISSUE THREAD

**Issue by davidfrisch** [project-chip/matter.js#660]
When configuring the WiFi settings in the Matter.js shell, the SSID is not correctly recognized when it contains spaces.

For instance, if my SSID is "My Home" and the password is 1234, the content of the generated files is as follows:
I ran: 
```
config wifi-credentials set "My Home" 1234
```
Generated files:
```
# Node.WiFiSsid
"\"My"
```

```
#Node.WiFiPassword
"Home\""
```

**Comment by Apollon77** [comment]
Hm ... I need tocheck why yargs is behaving that way.
