### ISSUE TITLE
Any plans to  create a class for WindowCoveringDevices ?

### ISSUE THREAD

**Issue by seriousme** [project-chip/matter.js#697]
Hi,

I got my on-off devices working (works great, thanks for that !), but now I would like to add a capability for WindowCoveringDevices

I checked and could not find any equivalent for WindowCoveringDevices of:

https://github.com/project-chip/matter.js/blob/main/packages/matter.js/src/device/OnOffDevices.ts

Are there plans to add such an equivalent ?
Or are there other (easy ;-)) ways to create a WindowCoveringDevice cluster?

Kind regards,
Hans

**Comment by Apollon77** [comment]
Yes, we are currently about to finalize the new Devices High level API which will have full support for this ... I will leave open and poke once we have a nightly to try it

**Comment by Apollon77** [comment]
PS: If you need it faster then check out what the current device classes do and adopt it for WC ... in fact all clusters are there, just implementation needed.

**Comment by seriousme** [comment]
Thanks for the quick reply !

I have time, so I'll wait for the nightly :-)

KInd regards,
Hans

**Comment by Apollon77** [comment]
If you like a "pre look" ...will look like that https://github.com/project-chip/matter.js/blob/device-gen/packages/matter-node.js-examples/src/examples/IlluminatedRollerShade.ts

**Comment by seriousme** [comment]
Thanks, it looks less complex than the current interface.

**Comment by Apollon77** [comment]
compared to what? Ok the other examples have a lot of "boiler plate code" to make anything configurable ... this is completely missing in the example link I sent you ... because this adapter just logs stuff :-) The other examples can be used as CLI tool directly. Or what you mean?

**Comment by seriousme** [comment]
When I compare:

https://github.com/project-chip/matter.js/blob/dfc6d1e100f7d5d48dfc4569f1dcfc07b830b25e/packages/matter-node.js-examples/src/examples/DeviceNode.ts#L151-L238

to:

https://github.com/project-chip/matter.js/blob/913e35000f0bdcdd88f3cf1f35fd671f85e32dfc/packages/matter-node.js-examples/src/examples/IlluminatedRollerShade.ts#L96-L130

The latter looks more simple, but maybe that is just visual due to the comments sections and the BLE inclusion.
Once I really start coding with it I'll probably have a better feel for it ;-)

**Comment by Apollon77** [comment]
All right ... I will also try to simplify the examples code wise a bit to have better focus on the relevant stuff :-)

Main difference is that some examples really work as "cli tools" and so there is more code needed

**Comment by Apollon77** [comment]
I also tried to simplify the examples a bit (beside DevicesFull because it's goal is to show all the fancieness) ... 

WDYT? 

https://github.com/project-chip/matter.js/blob/03ee51b6505407f62f8bf3a1d96310f0d11cef5f/packages/matter-node.js-examples/src/examples/DeviceNode.ts

**Comment by seriousme** [comment]
It clearly shows how to use the API by putting the CLI stuff at the end.

Nice work!

The CLI stuff feels a bit repetitive, maybe something like 

 ```javascript
getNumberVar(key, default).{
  return environment.vars.number(key) ?? deviceStorage.get(key, default);
}

const passcode = getNumberVar("passcode", 20202021);
const discriminator = getNumberVar("discriminator", 3840) ;
```

could help ;-)

**Comment by Apollon77** [comment]
0.8 landed also first nightly is available on npm using @dev ... so have fun
