### ISSUE TITLE
Cannot find module '@abandonware/noble' or its corresponding type declarations

### ISSUE THREAD

**Issue by huytungst** [project-chip/matter.js#707]
My system: 
- Ubuntu 22.04.4 LTS;
- Core i5 8th gen (LG-Gram laptop, on-board Bluetooth 4.2);
- Node.js 18.18.0 LTS; 
- matter.js 0.7.5; 
- npm 9.8.1;
- Python 3.10.12.

I'm not sure if this is a bug or a problem with my setup and devices.

At matter.js root path, "npm install" or "sudo npm install" can not find module '@abandonware/noble':

.. prepare
.. npm run build-clean
.. build-clean
.. node packages/matter.js-tools/bin/build.js --workspaces --clean

Building @project-chip/matter.js-tools@0.7.5
  v heavy_check_mark: Clean (0.01s)
  v heavy_check_mark: Generate type declarations (2.2s)
  v heavy_check_mark: Install type declarations (0.05s)
  v heavy_check_mark: Transpile library to ESM (0.05s)
  v heavy_check_mark: Transpile tests to ESM (0.01s)
  v heavy_check_mark: Transpile library to CJS (0.03s)
  v heavy_check_mark: Transpile tests to CJS (0.01s)

Building @project-chip/matter.js@0.7.5
  v heavy_check_mark: Clean (0.13s)
  v heavy_check_mark: Generate type declarations (16s)
  v heavy_check_mark: Install type declarations (0.54s)
  v heavy_check_mark: Transpile library to ESM (0.26s)
  v heavy_check_mark: Transpile tests to ESM (0.05s)
  v heavy_check_mark: Transpile library to CJS (0.28s)
  v heavy_check_mark: Transpile tests to CJS (0.05s)

Building @project-chip/matter-node.js@0.7.5
  v heavy_check_mark: Clean (0.01s)
  v heavy_check_mark: Generate type declarations (3.3s)
  v heavy_check_mark: Install type declarations (0.06s)
  v heavy_check_mark: Transpile library to ESM (0.02s)
  v heavy_check_mark: Transpile tests to ESM (0.03s)
  v heavy_check_mark: Transpile library to CJS (0.02s)
  v heavy_check_mark: Transpile tests to CJS (0.03s)

Building @project-chip/matter-node-ble.js@0.7.5
  v heavy_check_mark: Clean (0s)
  ✗ Terminating due to type errors (0.89s)
packages/matter-node-ble.js/src/ble/NobleBleClient.ts:7:33 - error TS2307: Cannot find module '@abandonware/noble' or its corresponding type declarations.
7 import type { Peripheral } from "@abandonware/noble";
                                  ~~~~~~~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/NobleBleClient.ts:15:26 - error TS2307: Cannot find module '@abandonware/noble' or its corresponding type declarations.
15 let noble: typeof import("@abandonware/noble");
                            ~~~~~~~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/NobleBleClient.ts:51:33 - error TS7006: Parameter 'state' implicitly has an 'any' type.
51         noble.on("stateChange", state => {
                                   ~~~~~
packages/matter-node-ble.js/src/ble/NobleBleClient.ts:62:30 - error TS7006: Parameter 'peripheral' implicitly has an 'any' type.
62         noble.on("discover", peripheral => this.handleDiscoveredDevice(peripheral));
                                ~~~~~~~~~~
packages/matter-node-ble.js/src/ble/NobleBleClient.ts:107:13 - error TS7006: Parameter 'serviceData' implicitly has an 'any' type.
107             serviceData => serviceData.uuid === BLE_MATTER_SERVICE_UUID,
                ~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BleScanner.ts:7:33 - error TS2307: Cannot find module '@abandonware/noble' or its corresponding type declarations.
7 import type { Peripheral } from "@abandonware/noble";
                                  ~~~~~~~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/NobleBleChannel.ts:7:49 - error TS2307: Cannot find module '@abandonware/noble' or its corresponding type declarations.
7 import type { Characteristic, Peripheral } from "@abandonware/noble";
                                                  ~~~~~~~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/NobleBleChannel.ts:191:52 - error TS7006: Parameter 'data' implicitly has an 'any' type.
191         characteristicC2ForSubscribe.once("data", (data, isNotification) => {
                                                       ~~~~
packages/matter-node-ble.js/src/ble/NobleBleChannel.ts:191:58 - error TS7006: Parameter 'isNotification' implicitly has an 'any' type.
191         characteristicC2ForSubscribe.once("data", (data, isNotification) => {
                                                             ~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/NobleBleChannel.ts:224:50 - error TS7006: Parameter 'data' implicitly has an 'any' type.
224         characteristicC2ForSubscribe.on("data", (data, isNotification) => {
                                                     ~~~~
packages/matter-node-ble.js/src/ble/NobleBleChannel.ts:224:56 - error TS7006: Parameter 'isNotification' implicitly has an 'any' type.
224         characteristicC2ForSubscribe.on("data", (data, isNotification) => {
                                                           ~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:25:26 - error TS2307: Cannot find module '@abandonware/bleno' or its corresponding type declarations.
25 let Bleno: typeof import("@abandonware/bleno");
                            ~~~~~~~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:42:18 - error TS4112: This member cannot have an 'override' modifier because its containing class 'BtpWriteCharacteristicC1' does not extend another class.
42         override onWriteRequest(
                    ~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:52:31 - error TS2339: Property 'RESULT_SUCCESS' does not exist on type 'BtpWriteCharacteristicC1'.
52                 callback(this.RESULT_SUCCESS);
                                 ~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:55:31 - error TS2339: Property 'RESULT_UNLIKELY_ERROR' does not exist on type 'BtpWriteCharacteristicC1'.
55                 callback(this.RESULT_UNLIKELY_ERROR);
                                 ~~~~~~~~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:68:24 - error TS4112: This member cannot have an 'override' modifier because its containing class 'BtpIndicateCharacteristicC2' does not extend another class.
68         override async onSubscribe(maxValueSize: number, updateValueCallback: (data: Buffer) => void) {
                          ~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:74:24 - error TS4112: This member cannot have an 'override' modifier because its containing class 'BtpIndicateCharacteristicC2' does not extend another class.
74         override async onUnsubscribe() {
                          ~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:79:18 - error TS4112: This member cannot have an 'override' modifier because its containing class 'BtpIndicateCharacteristicC2' does not extend another class.
79         override onIndicate() {
                    ~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:93:18 - error TS4112: This member cannot have an 'override' modifier because its containing class 'BtpReadCharacteristicC3' does not extend another class.
93         override onReadRequest(offset: number, callback: (result: number, data?: Buffer) => void) {
                    ~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:97:31 - error TS2339: Property 'RESULT_SUCCESS' does not exist on type 'BtpReadCharacteristicC3'.
97                 callback(this.RESULT_SUCCESS, data);
                                 ~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:100:31 - error TS2339: Property 'RESULT_INVALID_OFFSET' does not exist on type 'BtpReadCharacteristicC3'.
100                 callback(this.RESULT_INVALID_OFFSET);
                                  ~~~~~~~~~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:148:33 - error TS7006: Parameter 'state' implicitly has an 'any' type.
148         Bleno.on("stateChange", state => {
                                    ~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:161:28 - error TS7006: Parameter 'clientAddress' implicitly has an 'any' type.
161         Bleno.on("accept", clientAddress => {
                               ~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:167:32 - error TS7006: Parameter 'clientAddress' implicitly has an 'any' type.
167         Bleno.on("disconnect", clientAddress => {
                                   ~~~~~~~~~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:181:32 - error TS7006: Parameter 'rssi' implicitly has an 'any' type.
181         Bleno.on("rssiUpdate", rssi => {
                                   ~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:186:31 - error TS7006: Parameter 'mtu' implicitly has an 'any' type.
186         Bleno.on("mtuChange", mtu => {
                                  ~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:190:38 - error TS7006: Parameter 'error' implicitly has an 'any' type.
190         Bleno.on("advertisingStart", error => {
                                         ~~~~~
packages/matter-node-ble.js/src/ble/BlenoBleServer.ts:203:33 - error TS7006: Parameter 'error' implicitly has an 'any' type.
203         Bleno.on("servicesSet", error => {
                                    ~~~~~
npm ERR! code 1
npm ERR! path /home/mylinux/Desktop/local/matter-js/matter.js
npm ERR! command failed
npm ERR! command sh -c npm run build-clean
npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-02-27T08_12_02_027Z-debug-0.log

**Comment by Apollon77** [comment]
This happens when there was an issue with "npm install" and it did not istalled the BLE packages. to see the exact issue please try

`npm install --forground-scripts` and post output

**Comment by Apollon77** [comment]
PS: One question: Why you install it that way? Cloning the repo andbuilding fromthere is a valid approachif you like to participate with the core library development.If this is not what you wanted just install the matter-node.js package and use this in your project

**Comment by huytungst** [comment]
Thank you for your quick reply.

I tried `npm install --foreground-scripts`, and the output was still the same as above. 

Actually I'm trying to install `matter-node-ble.js` because when I played with Matter Node Shell (`npm install @project-chip/matter-node-shell.js`, then `npm run shell`), I was told that:

`Error: Cannot find module '/home/mylinux/Desktop/local/matter/matter.js/node_modules/@project-chip/matter-node-ble.js/dist/cjs/ble/export.js'`

~/Desktop/local/matter/matter.js$ npm run shell

> shell
> matter-run packages/matter-node-shell.js/src/app.ts
node:internal/modules/cjs/loader:573
      throw e;
      ^
Error: Cannot find module '/home/mylinux/Desktop/local/matter/matter.js/node_modules/@project-chip/matter-node-ble.js/dist/cjs/ble/export.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1098:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1091:15)
    at resolveExports (node:internal/modules/cjs/loader:567:14)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/mylinux/Desktop/local/matter/matter.js/packages/matter-node-shell.js/src/app.ts:7:25)
    at Module._compile (node:internal/modules/cjs/loader:1256:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/mylinux/Desktop/local/matter/matter.js/node_modules/@project-chip/matter-node-ble.js/package.json'
}
Node.js v18.18.0
node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^
Process node exited with code 1
(Use `node --trace-uncaught ...` to show where the exception was thrown)
Node.js v18.18.0



~/Desktop/local/matter/matter.js/packages/matter-node-shell.js$ npm run shell

> @project-chip/matter-node-shell.js@0.7.5 shell
> matter-run src/app.ts
node:internal/modules/cjs/loader:573
      throw e;
      ^
Error: Cannot find module '/home/mylinux/Desktop/local/matter/matter.js/node_modules/@project-chip/matter-node-ble.js/dist/cjs/ble/export.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1098:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1091:15)
    at resolveExports (node:internal/modules/cjs/loader:567:14)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/mylinux/Desktop/local/matter/matter.js/packages/matter-node-shell.js/src/app.ts:7:25)
    at Module._compile (node:internal/modules/cjs/loader:1256:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/mylinux/Desktop/local/matter/matter.js/node_modules/@project-chip/matter-node-ble.js/package.json'
}
Node.js v18.18.0
node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^
Process node exited with code 1
(Use `node --trace-uncaught ...` to show where the exception was thrown)
Node.js v18.18.0
npm ERR! Lifecycle script `shell` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @project-chip/matter-node-shell.js@0.7.5
npm ERR!   at location: /home/mylinux/Desktop/local/matter/matter.js/packages/matter-node-shell.js

**Comment by huytungst** [comment]
I think I solved this issue with installing "make":

`sudo apt-get install -y build-essential`

Thank you for your supports ~
