### ISSUE TITLE
implement Aggregate Bridging Cluster

### ISSUE THREAD

**Issue by vves** [project-chip/matter.js#71]
Implement 9.12 of the Matter-1.0-Core-Specification "Bridge for non-Matter devices"

**Comment by vves** [comment]
@Apollon77 I thought there was a Endpoints refactor that you were working on before the Aggregate endpoint could be built per this Discussion on the node-matter project:  https://github.com/mfucci/node-matter/discussions/57

If you think this project is ready for the Bridging (Aggregate) Cluster based of the main branch I'll get started.

Cheers!

**Comment by Apollon77** [comment]
Closed because clusters are already there. The coming High level API will introduce an easy way to use it
