### ISSUE TITLE
Bridged Devices not found

### ISSUE THREAD

**Issue by louisvangeldrop** [project-chip/matter.js#767]
BridgedDevicesNode is not found. ...src/examples/BridgedDeviceNode.ts

**Comment by Apollon77** [comment]
Can you please be a bit more specific? Is this a link in the dodcs you mention or what?

**Comment by louisvangeldrop** [comment]
Sorry for the missing information:

 npm run matter-bridge  -- -type socket -num 2 -on1 "echo on1" -off1 "echo off1" -type2 socket -on2 "echo on2" -off2 "echo off2"

> matter-run packages/matter-node.js-examples/src/examples/BridgedDevicesNode.ts -type socket -num 2 -on1 echo on1 -off1 echo off1 -type2 socket -on2 echo on2 -off2 echo off2

node:internal/modules/cjs/loader:1145
  throw err;
  ^

Error: Cannot find module 'C:\Users\louis\projecten\matter.js\packages\matter-node.js-examples\dist\esm\examples\BridgedDevicesNode.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by Apollon77** [comment]
Hm ... which version you use?

How you installed it?

**Comment by louisvangeldrop** [comment]
packages\matter-node.js-examples\package.json contains the line: 
"matter-bridge": "matter-run  src/examples/BridgedDevicesNode.ts",

while the actual filename is: src/examples/BridgedDeviceNode.ts. without an "s"

**Comment by louisvangeldrop** [comment]
Version 0.8.0-alpha.0-20240328-f7f45db5. Installed with the command: npm install

**Comment by Apollon77** [comment]
Thank you, I will provide a fix for the next nightly!

**Comment by Apollon77** [comment]
I rrenamed the JS file as expected ... there should be a new nightly, please try

**Comment by louisvangeldrop** [comment]
It is working now. THX for the quick response.
My compliments for this great project !!!

**Comment by louisvangeldrop** [comment]
I am using the matter-bridge in order to connect an ESP32- running moddable javascript temperature/humidity sensor.

**Comment by Apollon77** [comment]
Pohhh interesting ... and yes ... moddable project is awesome!
