### ISSUE TITLE
GeneralDiagnosticsCluster NetworkInterfaces attribute in CommissioningServer

### ISSUE THREAD

**Issue by Luligu** [project-chip/matter.js#873]
Hi,
testing Matterbridge with Home Assistant I noticed in the HA logs that they report like errors the lack of NetworkInterfaces attribute in the GeneralDiagnosticsCluster of the CommissioningServer.
I added it in Matterbridge and now the HA logs are clear and the commissioning now takes less then a second.
I think that, even if it is not mandatory, would be useful to add the NetworkInterfaces attribute directly in matter.js.
Probably also other controllers may use it for diagnostic or pairing process (also Apple Home now commission Matterbridge immediatly).
For the same reason (reported errors in HA logs) I also added productId: OptionalFixedAttribute, to BridgedDeviceBasicInformation and all errors disappeared from logs.
It would be useful to add it as well like optional fixed attribute.
Thanks.

**Comment by Apollon77** [comment]
For the ProductId in bridged Device Basic Info I would rather open an issue on Home Assistant side because expecting this attribute which is explicitely removed in the specs makes no sense.
