### ISSUE TITLE
matter-device cli error in ubuntu 20.04

### ISSUE THREAD

**Issue by hassan-xy** [project-chip/matter.js#899]

**Comment by hassan-xy** [comment]
Hi team,
I intended to run some examples of mater-node.js-examples using command "**npm i -g @project-chip/matter-node.js-examples**". On entering matter-device I get the error message.
 Can you  guys update the issue I am facing. Also what distro are you guys using(just asking)?
![image](https://github.com/project-chip/matter.js/assets/125990448/936827e6-5743-41c5-8fb9-80a283b8189a)

**Comment by Apollon77** [comment]
Hm ....very interesting and I have no clue what happens there. It seems he executes that very strange. did you tried the npm command instead of "the binary"?

**Comment by hassan-xy** [comment]
I will try and update.
Also I am not running this on a raspberry pi or BBB board. I am running on a custom dev board using Ubuntu 20.04 as OS. I am not sure whats going wrong here.

**Comment by hassan-xy** [comment]
I tried to pull the repo and build using **npm install** but get the heap out of memory error.
![image](https://github.com/project-chip/matter.js/assets/125990448/490e348f-6f7b-4942-b998-a5d5520b4fbf)

Please try to look into this and guide me.

**Comment by Apollon77** [comment]
Head error is a "normal" OOM" error. please provide "free -m" output from that host. The build process could use some RAM yes, so also question: WHy you checked out the matter.js repo and build yourself and not use the npm packages that contain anything aready pre-built?

**Comment by hassan-xy** [comment]
Well looks like I shouldnt have tried it.
**npm install @project-chip/matter-node.js --save** builds with no errors.
**npm install @project-chip/matter-node.js-examples** also builds.
The issue arises when I run **matter-device** I get the error I earlier posted. I also tried **npm run matter-device** but that doesnt work either. 
![image](https://github.com/project-chip/matter.js/assets/125990448/19bc6418-c8e3-4f86-ab38-57a055c61b9f)

@Apollon77 You have any suggestions for me?

**Comment by lauckhart** [comment]
The issue with matter-device is a missing shebang, I fixed in #933.  In the meantime though you can run the example directly via `node` like in #898.  For the examples you can see what scripts the commands map to here:
https://github.com/project-chip/matter.js/blob/8c160a013bbd8e9a3b66c38218f360af8310f1db/packages/matter-node.js-examples/package.json#L48-L61

**Comment by Apollon77** [comment]
fixes are in latest nightlies

**Comment by hassan-xy** [comment]
Hi guys,
I donwloaded the lastest [Release v0.10.0-alpha.0-20240611-823c6da5] but cant find BridgedDevicesNode.js file in the zip file. Seems like almost all the files are missing. 
Can you guy check for once and update me.
Thanks

**Comment by Apollon77** [comment]
Which zip file? We do not publish releases on github, please install using npm
