### ISSUE TITLE
Backward compatibility for ACL logic failing on Google Home

### ISSUE THREAD

**Issue by JimBuzbee** [project-chip/matter.js#913]
Using the baseline that includes the new ACL logic, a previously commissioned device never comes online with Google Home.

Lots of errors in the log file like:

 _2024-05-30 12:35:55.413 ERROR  SubscriptionHandler  Error reading event !RootNode(0x0)/GeneralDiagnostics(0x33)/bootReason(0x3): (126) Access to 0/0x33 denied on secure/41269._

**Comment by Apollon77** [comment]
Ok, after checvk it is because Google just added one fabric but accessed with two ...
