### ISSUE TITLE
Examples Project: Running `DeviceNode` on the fly does not work

### ISSUE THREAD

**Issue by foxriver76** [project-chip/matter.js#948]
![Bildschirmfoto vom 2024-06-11 12-26-09](https://github.com/project-chip/matter.js/assets/25484431/45711f2a-0711-4e9d-8b2b-287339df7aef)

This only happens when using the hot reload TS option, executing directly via `node node_modules/@project-chip/matter-node.js-examples/dist/esm/examples/DeviceNode.js` works fine

**Comment by lauckhart** [comment]
@foxriver76 thanks for the detail.  I added logic in #949 that disables building when the matter-node.js-examples package is installed via NPM so the "npm run" command should work.

**Comment by Apollon77** [comment]
@foxriver76 should be merged soon and be in next bnightly, so would be cool if you could validate it thursday ;-) Thank you!
