### ISSUE TITLE
Not sure how to use this js file

### ISSUE THREAD

**Issue by hassan-xy** [project-chip/matter.js#951]
![image](https://github.com/project-chip/matter.js/assets/125990448/3a51b9d0-916e-42ff-b899-92cd6a466bbb)
Well i tried if they run but seems like nothing happens. I might be completely wrong here. I have added both the Bleno and the other module.
PS: I intend to run my device as a bridge gateway.

**Comment by lauckhart** [comment]
These files are modules that export library implementation (as is the case for most files in NPM packages).  If you're interested in matter.js's BLE support you can look at how BleNode is used in the examples, e.g. https://github.com/project-chip/matter.js/blob/f969d1e699e1877a240e42d238fbea366f466f30/packages/matter-node.js-examples/src/examples/DeviceNodeFull.ts
